"""新增用户表、用户关系表、角色表、日志表

Revision ID: 8d8214153797
Revises: 2da8a653bd39
Create Date: 2025-04-22 13:54:50.539010+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8d8214153797'
down_revision: Union[str, None] = '2da8a653bd39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='角色名称'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='角色描述'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='密码哈希'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='邮箱'),
    sa.Column('full_name', sa.String(length=100), nullable=True, comment='全名'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否激活'),
    sa.Column('is_superuser', sa.Boolean(), nullable=False, comment='是否超级管理员'),
    sa.Column('last_login', sa.DateTime(), nullable=True, comment='最后登录时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('login_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('login_time', sa.DateTime(), nullable=True, comment='登录时间'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='登录IP地址'),
    sa.Column('user_agent', sa.Text(), nullable=True, comment='用户代理信息'),
    sa.Column('status', sa.Integer(), nullable=False, comment='登录状态：0-失败，1-成功'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('scheduled_task',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('task_name', sa.String(length=50), nullable=False, comment='任务名称'),
    sa.Column('controller_id', sa.String(length=32), nullable=False, comment='控制器ID'),
    sa.Column('task_type', sa.Integer(), nullable=False, comment='任务类型：1-消息推送，2-好友添加，3-频道检索'),
    sa.Column('cron_expression', sa.String(length=100), nullable=False, comment='Cron表达式'),
    sa.Column('task_data', sa.JSON(), nullable=True, comment='任务数据'),
    sa.Column('status', sa.Integer(), nullable=True, comment='状态：0-禁用，1-启用'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['controller_id'], ['controller.controller_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('scheduledtask')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduledtask',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('task_name', mysql.VARCHAR(length=50), nullable=False, comment='任务名称'),
    sa.Column('controller_id', mysql.VARCHAR(length=32), nullable=False, comment='控制器ID'),
    sa.Column('task_type', mysql.INTEGER(), autoincrement=False, nullable=False, comment='任务类型：1-消息推送，2-好友添加，3-频道检索'),
    sa.Column('cron_expression', mysql.VARCHAR(length=100), nullable=False, comment='Cron表达式'),
    sa.Column('task_data', mysql.JSON(), nullable=True, comment='任务数据'),
    sa.Column('status', mysql.INTEGER(), autoincrement=False, nullable=True, comment='状态：0-禁用，1-启用'),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['controller_id'], ['controller.controller_id'], name='scheduledtask_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('scheduled_task')
    op.drop_table('user_roles')
    op.drop_table('login_logs')
    op.drop_table('user')
    op.drop_table('role')
    # ### end Alembic commands ###
