"""Initial migration

Revision ID: 2da8a653bd39
Revises: 
Create Date: 2025-04-22 13:36:48.199570+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2da8a653bd39'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.String(length=32), nullable=False, comment='客户端唯一标识'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='客户端名称'),
    sa.Column('status', sa.Integer(), nullable=True, comment='状态：0-离线，1-在线'),
    sa.Column('ip_address', sa.String(length=15), nullable=True, comment='客户端IP地址'),
    sa.Column('last_online_time', sa.DateTime(), nullable=True, comment='最后在线时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    op.create_table('controller',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('controller_id', sa.String(length=32), nullable=False, comment='控制器唯一标识'),
    sa.Column('client_id', sa.String(length=32), nullable=False, comment='所属客户端ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='控制器名称'),
    sa.Column('status', sa.Integer(), nullable=True, comment='状态：0-停止，1-运行中'),
    sa.Column('login_status', sa.Integer(), nullable=True, comment='登录状态：0-未登录，1-已登录'),
    sa.Column('qr_code_url', sa.Text(), nullable=True, comment='登录二维码URL'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.client_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('controller_id')
    )
    op.create_table('message',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('controller_id', sa.String(length=32), nullable=False, comment='控制器ID'),
    sa.Column('message_type', sa.Integer(), nullable=False, comment='消息类型：1-文本，2-图片，3-文件'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('sender_id', sa.String(length=32), nullable=False, comment='发送者ID'),
    sa.Column('receiver_id', sa.String(length=32), nullable=False, comment='接收者ID'),
    sa.Column('chat_type', sa.Integer(), nullable=False, comment='聊天类型：1-私聊，2-群聊，3-频道'),
    sa.Column('status', sa.Integer(), nullable=True, comment='状态：0-待发送，1-已发送，2-发送失败'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['controller_id'], ['controller.controller_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduledtask',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('task_name', sa.String(length=50), nullable=False, comment='任务名称'),
    sa.Column('controller_id', sa.String(length=32), nullable=False, comment='控制器ID'),
    sa.Column('task_type', sa.Integer(), nullable=False, comment='任务类型：1-消息推送，2-好友添加，3-频道检索'),
    sa.Column('cron_expression', sa.String(length=100), nullable=False, comment='Cron表达式'),
    sa.Column('task_data', sa.JSON(), nullable=True, comment='任务数据'),
    sa.Column('status', sa.Integer(), nullable=True, comment='状态：0-禁用，1-启用'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['controller_id'], ['controller.controller_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheduledtask')
    op.drop_table('message')
    op.drop_table('controller')
    op.drop_table('client')
    # ### end Alembic commands ###
